services:
 postgres:
  build:
   context: postgres
  image: postgres
  container_name: postgres_container
  environment:
   POSTGRES_USER: admin
   POSTGRES_PASSWORD: password
   PGDATA: /data/postgres
  volumes:
  - postgres:/data/postgres
  ports:
  - "5432:5432"
  networks:
  - postgresNetwork
  restart: unless-stopped
  
 pgadmin:
  container_name: pgAdmin_container
  image: dpage/pgadmin4
  environment:
   PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
   PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-password}
   PGADMIN_CONFIG_SERVER_MODE: 'False'
  volumes:
   - pgadmin:/var/lib/pgadmin
  ports:
   - "5050:80"
  networks:
   - postgresNetwork
  restart: unless-stopped
  
networks:
 microserviceNetwork:
  driver: bridge
 postgresNetwork:
  driver: bridge
    
volumes:
 postgres:
 pgadmin:
